### ISSUE TITLE
Design question?  Why is explicit disconnect done with each query? This is a costly task and is not usually considered as best practice

### ISSUE THREAD

**Issue by Jibun-no-Kage** [RickyVaughn2/node-red-mysql-r2#1]
Design question?  Why is explicit disconnect done with each query? This is noted in the documentation, this is a costly task and is not usually considered as best practice, to connect and disconnect continually.  Ultimately, a connection time out a some point is one thing, but the documentation implies that is not the case.  If I have a NR flow that is doing frequent queries, updates, etc., frequency connection and disconnection is not a good design strategy, IMHO.

**Comment by RickyVaughn2** [comment]
I have several raspberry pi systems running in the wild collecting several data points.  They all send the data to an AWS MySQL instance.  The issue I personally had with the node-red-node-mysql was that it was creating hundreds of connections from each device, tens of thousands across all the devices.  I would eventually hit a wall.  I wrote this to kill the connection each time and now have had no issues.  

I am certainly open to suggestions.  Is there a better way for me to deal with my specific issue?  Would you like to see an option to turn this particular feature on and off?

**Comment by Jibun-no-Kage** [comment]
Enable connection pooling?

**Comment by RickyVaughn2** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/7469999/230555962-a47aaf3f-aa94-4f0f-bb07-c6e3b8e6bf7d.png)

**Comment by RickyVaughn2** [comment]
Actually, going to add the ability to turn pooling on and off all together.  Should have the new code pushed over the weekend.

**Comment by Jibun-no-Kage** [comment]
Excellent!  And, if someone has configured the SQL server poorly for the demand level, this will still work, but also, provide feedback that the SQL server may (likely) need to be optimized.  Of course, any SQL admin should be on the ball, but, well, sometimes things are a surprise.

**Comment by RickyVaughn2** [comment]
done

**Comment by Jibun-no-Kage** [comment]
Cool, thanks for the active support, greatly appreciated.
