### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by Santtu1980** [RickyVaughn2/node-red-mysql-r2#2]
This nor any else mysql modules does not work with transactions.
I have to insert rows to two different tables and all inserts should success.

Shortly this is my msg.sql:
START TRANSACTION;
INSERT INTO header 
(datetime, job_id, somedata ) 
VALUES 
('2023-4-5T8:43:14', '123', 'asd');
SELECT @id := LAST_INSERT_ID();
INSERT INTO details 
(measured_value, setpoint_value, header_id) 
VALUES (430, 440, @id), (480, 480, @id), (190, 200, @id);
COMMIT;

This works if I copy-paste this to mysql workbench.

**Comment by RickyVaughn2** [comment]
I will try to help you.  Let me know exactly how you are using the node.

**Comment by RickyVaughn2** [comment]
Here is a quick example:

![image](https://user-images.githubusercontent.com/7469999/230528874-5cf6dbcf-2b45-4bdf-90dc-6f2d3740b634.png)
![image](https://user-images.githubusercontent.com/7469999/230528912-4a0a9701-4f86-4ac6-b16b-f0b0827708e1.png)
![image](https://user-images.githubusercontent.com/7469999/230528967-e8794eff-e627-4e84-96a3-96a262686d89.png)


`[{"id":"3c350ce0b170aad3","type":"mysql-r2","z":"82c2857390310b89","name":"","host":"","database":"","username":"","password":"","sql":"","x":560,"y":180,"wires":[["d20b1c8000dc71ce"]]},{"id":"d1481d6f93bbcf0a","type":"inject","z":"82c2857390310b89","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":240,"y":180,"wires":[["590d340857acb7b1"]]},{"id":"590d340857acb7b1","type":"function","z":"82c2857390310b89","name":"function 1","func":"\n\nmsg={\n    host:\"localhost\",\n    database:\"database_name\",\n    username:\"username\",\n    password:\"password\",\n    sql:\"select * table\"\n}\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":400,"y":180,"wires":[["3c350ce0b170aad3"]]},{"id":"d20b1c8000dc71ce","type":"debug","z":"82c2857390310b89","name":"debug 1","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":720,"y":180,"wires":[]},{"id":"b48cfb2c6939c9c0","type":"function","z":"82c2857390310b89","name":"function 2","func":"\nmsg={\n    host: \"localhost\",\n    database: \"database_name\",\n    username: \"username\",\n    password: \"password\",\n    sql: \"REPLACE INTO table (column1, column2) VALUES ('column 1 data', 'column 2 data');\"\n}\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":400,"y":240,"wires":[["3c350ce0b170aad3"]]},{"id":"d03fb338209a28c5","type":"inject","z":"82c2857390310b89","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":240,"y":240,"wires":[["b48cfb2c6939c9c0"]]}]`

**Comment by Santtu1980** [comment]
This example is from mysql manual:

-- 1. start a new transaction
START TRANSACTION;

-- 2. Get the latest order number
SELECT 
    @orderNumber:=MAX(orderNUmber)+1
FROM
    orders;

-- 3. insert a new order for customer 145
INSERT INTO orders(orderNumber,
                   orderDate,
                   requiredDate,
                   shippedDate,
                   status,
                   customerNumber)
VALUES(@orderNumber,
       '2005-05-31',
       '2005-06-10',
       '2005-06-11',
       'In Process',
        145);
        
-- 4. Insert order line items
INSERT INTO orderdetails(orderNumber,
                         productCode,
                         quantityOrdered,
                         priceEach,
                         orderLineNumber)
VALUES(@orderNumber,'S18_1749', 30, '136', 1),
      (@orderNumber,'S18_2248', 50, '55.09', 2); 
      
-- 5. commit changes    
COMMIT;

<img width="797" alt="image" src="https://user-images.githubusercontent.com/38642576/230559924-09f627ad-d729-4268-a453-6be155a509b4.png">

**Comment by RickyVaughn2** [comment]
If I am understanding you correctly, you need to perform a query, then based on the output, perform an insert, and then perform another insert.  If anything fails, you want to undo everything.

Keep in mind that this does not have a 'commit' like some IDEs might have.  When you INSERT using any mysql node, it is instant.

Again, I may not be following you here, but you ...could... possibly do each step and check that it completed correctly.  If it fails, you would need to then DELETE the records you created and reset your orderNumber back.

I think it would look more like a function node going into a mysql node then into something that is checking on things with 2 outputs, one undoing what you just did, the other continuing to the next function.  You would need to ability to remember everything so that if the last step fails you can undo it all.  I am thinking something like a global or node level variable.

I am sure there are a 100 ways to do what you want to do and someone else may have a better idea.

**Comment by Santtu1980** [comment]
Thanks.
You understood completely correctly. I did it in my own way, pretty much as you described, by checking each INSERT and only proceeding if successful, and removing it if not.
