### ISSUE TITLE
different port

### ISSUE THREAD

**Issue by Tommie84** [RickyVaughn2/node-red-mysql-r2#3]
Hi,

im using a different port to connect to, since i have multiple databases running in containers.
but there is no possibility to add port 8101 for example.
when i add it to msg.host it gives the error it cannot find the address.
Can this be fixed or added?

**Comment by RickyVaughn2** [comment]
I will add the ability to select a custom port in my next release.  :)  

Until then, I will keep this open.

**Comment by RickyVaughn2** [comment]
I was able to take care of it quickly after all.
